
default: 
	make -C ..

run : 
	make -C .. run

run2 : 
	make -C .. run2

run3 : 
	make -C .. run3

clean:
	make -C .. clean


.PHONY : default run run2 clean





# default: launch1.native
# 
# launch1.native : *.ml
# 	ocamlbuild -lib unix launch1.native
# 
# run : launch1.native
# 	./launch1.native
# 
# clean:
# 	ocamlbuild launch1.native -clean
# 
# 
# .PHONY : default run clean



